// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"basic_resources/launch/wasdKeyMZ","status":true,"description":"It is a plugin that corresponds to the wasd move.","parameters":{}},
{"name":"Viet-plugin/JumpAttackMotion","status":true,"description":"Customizes the attack method and motion for Actor to jump to the target then return.","parameters":{"weaponTypeIds":"1,2,3"}},
{"name":"Viet-plugin/PictureChoices","status":true,"description":"Allows players to have the ability to select from a collection of pictures.","parameters":{"minScale":"0.25","maxScale":"0.3","scalingSpeed":"0.04","confirmSpeed":"0.2","closeSpeed":"0.4","columns":"3","rows":"2"}},
{"name":"Viet-plugin/FaceActorText","status":true,"description":"Show face actor auto by script call in show text.","parameters":{}},
{"name":"basic_resources/official/PluginCommonBase","status":false,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"basic_resources/launch/SVActorPositionMZ","status":false,"description":"[Ver1.1.5]Change actors' position on screen at sideview battle.","parameters":{"actor1 Xpos":"600","actor1 Ypos":"280","actor2 Xpos":"600 + 32","actor2 Ypos":"280 + 48","actor3 Xpos":"600 + 32 * 2","actor3 Ypos":"280 + 48 * 2","actor4 Xpos":"600 + 32 * 3","actor4 Ypos":"280 + 48 * 3"}},
{"name":"basic_resources/launch/SubMembersAttendBattle","status":false,"description":"[Ver1.1.0]Make Sub Members(=NPC) Attend Battle and does auto actions.","parameters":{"subMemberIdVal1":"1","subMemberIdVal2":"2","subMemberIdVal3":"3","subMemberIdVal4":"4"}},
{"name":"basic_resources/launch/MenuSubMembersMZ","status":false,"description":"Display sub members at menu window and map as followers","parameters":{"subMemberIdVal1":"1","subMemberIdVal2":"2","subMemberIdVal3":"3","subMemberIdVal4":"4","subMemberText":"Sub Members","displayIfNone":"false","subMemberNoneText":"None","DisplayOnMap":"true","additionalFollower":"4"}},
{"name":"basic_resources/launch/SimpleMsgSideViewMZ","status":false,"description":"[Ver1.2.0]At sideview battle, only display item/skill names.","parameters":{"displayAttack":"false","displayIcon":"true","doesShowDesc":"false","descTiming":"1"}},
{"name":"basic_resources/launch/SimplePassiveSkillMZ","status":false,"description":"[1.1.0]Make passive skill that change parameters and set traits.","parameters":{}},
{"name":"basic_resources/launch/StartUpFullScreen","status":false,"description":"Full Screen Startup","parameters":{"Shutdown":"Shutdown","DefaultFullScreen":"false","Immediate":"true","StartUpFullScreen":"Full Screen Startup","UseGameEnd":"true"}}
];
